// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvf8jMF-IjTECQkADxzX57wDBFvzPih7U',
    appId: '1:401331434450:web:57feaffedcbf077a494e0b',
    messagingSenderId: '401331434450',
    projectId: 'shop-radius-project-2f65e',
    authDomain: 'shop-radius-project-2f65e.firebaseapp.com',
    storageBucket: 'shop-radius-project-2f65e.firebasestorage.app',
    measurementId: 'G-52DFC1R4FZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8nVQSPtDqGwjVlwCQVulVb31PXhEENrI',
    appId: '1:401331434450:android:ac6978e14068b729494e0b',
    messagingSenderId: '401331434450',
    projectId: 'shop-radius-project-2f65e',
    storageBucket: 'shop-radius-project-2f65e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1zC344wkunidwv84XzzGNB66CiiPrw4U',
    appId: '1:401331434450:ios:38ba9b33bdf29aa4494e0b',
    messagingSenderId: '401331434450',
    projectId: 'shop-radius-project-2f65e',
    storageBucket: 'shop-radius-project-2f65e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1zC344wkunidwv84XzzGNB66CiiPrw4U',
    appId: '1:401331434450:ios:38ba9b33bdf29aa4494e0b',
    messagingSenderId: '401331434450',
    projectId: 'shop-radius-project-2f65e',
    storageBucket: 'shop-radius-project-2f65e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvf8jMF-IjTECQkADxzX57wDBFvzPih7U',
    appId: '1:401331434450:web:48cb16482918a5a0494e0b',
    messagingSenderId: '401331434450',
    projectId: 'shop-radius-project-2f65e',
    authDomain: 'shop-radius-project-2f65e.firebaseapp.com',
    storageBucket: 'shop-radius-project-2f65e.firebasestorage.app',
    measurementId: 'G-B1RRX7QQ58',
  );

}